// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LeftNav: typeof import('./src/components/LeftNav.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    NormalHeader: typeof import('./src/components/NormalHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
